# Atividade - 25/09/23

Documentação Numpy: https://numpy.org/doc/stable/

Enviar este arquivo preenchido com o nome do aluno para o e-mail: profbrunorespostas1@gmail.com e assunto: AD2301

In [1]:
#Substituir nome do aluno aqui
print("Luiz Felipe Silva de Oliveira")

Luiz Felipe Silva de Oliveira


### Questão 1:
Pesquisar na documentação da biblioteca numpy por propriedades e funções disponíveis para manipulação de Array de 1 dimensão (1darray) que não foram vistas em sala de aula. Citar cada uma delas com a explicação em forma de comentário e um exemplo.

Arquivo da aula sobre numpy: https://github.com/brunogomesifrn/respostas_ifrn/blob/main/python/Aulas/2023/numpy.ipynb

#### Propriedades - 1darray

In [6]:
# Importando bibliotea

import numpy as np

In [10]:
# A função 'zeros' cria um array a parti de uma sequência de elementos determinada através do parêntesses ().

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
# A função 'ones' cria um array a parti de uma sequência de elementos determinada através do parêntesses ().


np.ones(5)


array([1., 1., 1., 1., 1.])

#### Funções - 1darray

In [18]:
# Função 'concatenate' concatena dois ou mais arrays em um único array.


a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
c = np.array([5, 6, 7, 8])
d = np.array([5, 6, 7, 10])

np.concatenate((a, b, c, d ))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  5,  6,  7,  8,  5,  6,  7, 10])

In [52]:
# A função 'np.newaxis' aumentará as dimensões do seu array em uma dimensão quando usado uma vez

a = np.array([1, 2, 3, 4, 5, 6])

a2 = a[np.newaxis, :] 
a2.shape


(1, 6)

### Questão 2
Crie um exemplo de criação de um array de 2 dimensões (2darray).

In [53]:
# Função 'vstack' empilhá os array verticalmente 


a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

### Questão 3
Cite funções disponíveis no numpy que criam array de duas dimenões (2darray) já preenchido de forma automática.

In [62]:
# A função 'zeros' cria um array a parti de uma sequência de elementos determinada através do parêntesses ().


zero_array = np.zeros((3, 4))

print(zero_array)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [64]:
# A função 'ones' cria um array a parti de uma sequência de elementos determinada através do parêntesses ().

ones_array = np.ones((2, 3,4))
print(ones_array)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
