# 2darray - Array de 2 dimensão

In [5]:
import numpy as np

## Criação de um 2darray 

In [6]:
# Utiliza também a função array()

array_1 = np.array([[1, 2, 3], [4, 5, 6]])

In [7]:
print(array_1)

[[1 2 3]
 [4 5 6]]


In [10]:
array_teste = np.array([[2,1,7,3], [5,6,4,9]])
print(np.sort(array_teste))


[[1 2 3 7]
 [4 5 6 9]]


## Acessando elementos do array de 2 dimensão 

In [12]:
# Sempre na sequência: Linha X coluna. Se usa colchetes []

print(array_1[1][1])

5


In [13]:
print(array_1[0][2])

3


In [17]:
# linha 0; coluna 1

print(array_1[0,1])

30


In [15]:
# Para substituir um valor se utiliza colchetes também

array_1[0][1] = 30
print(array_1)

[[ 1 30  3]
 [ 4  5  6]]


In [16]:
array_1[1,0] = 15
print(array_1)

[[ 1 30  3]
 [15  5  6]]


## Propriedades para 2darray 

In [18]:
# shape - retorna a quantidade de elementos por dimensão 

print(array_1.shape)

(2, 3)


In [19]:
array_teste = np.array([2,5,6,7,8])
print(array_teste.shape)

(5,)


In [20]:
# size - quantidade total de elementos no array 

print(array_1.size)

6


In [21]:
# ndim - retorna a dimensão do array 

print(array_1.ndim)

2


## Funções para 2darray

In [23]:
# consum() - soma acumulada

print(array_1.cumsum())

[ 1 31 34 49 54 60]


In [26]:
# reshape - modifica a dimensão do array 

array_d1 = np.array([1,2,3,4,5,6])
array_2 = (array_d1.reshape(2,3))
print(array_2)

[[1 2 3]
 [4 5 6]]


In [27]:
''' a função cumsum gera um array de 1 dimensão. No exemplo a seguir,
foi acumulado com a função reshape(), 
que é executada em seguida gerando novamente o array de duas dimensões.
'''

print(array_1.cumsum().reshape(2,3))

[[ 1 31 34]
 [49 54 60]]


In [32]:
print(array_1.cumsum().reshape(2,3).shape)

(2, 3)


In [36]:
array_3 = np.array(range(1,11)).reshape(5,2)
print(array_3)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
